### ISSUE TITLE
Any Python 3 support plans?

### ISSUE THREAD

**Issue by moigagoo** [riffm/mint#37]
Hi,

It seems like mint can be adapted to Python 3 quite easily. I've just used 2to3 and it appears to work just fine (check out my fork https://github.com/moigagoo/mint).

Mint is quite impressive, we totally need it to get more attention :-)

Кстати, сейчас проект вообще жив?

**Comment by riffm** [comment]
Hello.

The project is dead. There were plans about more robust syntax and code
generation, but the lack of time killed everything.

On 29 мая 2014 г., at 18:21, Konstantin Molchanov notifications@github.com
wrote:

Hi,

It seems like mint can be adapted to Python 3 quite easily. I've just used
2to3 and it appears to work just fine (check out my fork
https://github.com/moigagoo/mint).

Mint is quite impressive, we totally need it to get more attention :-)

Кстати, сейчас проект вообще жив?

—
Reply to this email directly or view it on GitHub
https://github.com/riffm/mint/issues/37.
