### ISSUE TITLE
Ошибка сегментирования (?)

### ISSUE THREAD

**Issue by Harut** [riffm/mint#4]
Попытался написать следующую конструкцию, получил сигфолт:

<pre>
#def css(file):
    @link.rel(stylesheet).type(text/css).href({{ VALS.url_for_static(file) }})
#css('css/style.css')
</pre>

**Comment by riffm** [comment]
Ошибка была из за того, что реализация добавления selclosed тэга не соответствовала последнему API и одна из функций возвращала неправильные значения.

**Comment by riffm** [comment]
fixed
